[package]
name = "quarry"
version = "0.1.0"
edition = "2024"

[dependencies]
bytes = "1.10.1"
clap = { version = "4.5.48", features = ["derive"] }
miette = { version = "7.6.0", features = ["fancy"] }
